MvcNotes/Controllers/ManageCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MvcNotes.Models;
using MvcNotes.Repository;

namespace MvcNotes.Controllers
{
    [System.Web.Mvc.Authorize]
    public class ManageCategoriesController : Controller
    {
        private NotesRepository db = new NotesRepository();

        //
        // GET: /ManageCategories/

        public ActionResult Index()
        {
            int userId = (int)Membership.GetUser().ProviderUserKey;
            List<Category> lstCats = db.GelAllCategories(userId);
            return View(lstCats);
        }
        [HttpGet]
        public ActionResult AddSubCategory(int id = 0)
        {
            Category subCategory = new Category() {ParentId = id};
            return View(subCategory);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddSubCategory(Category category)
        {
            if (ModelState.IsValid)
            {
                int userId = (int)Membership.GetUser().ProviderUserKey;
                User owner = db.FindUser(userId);
                category.Owner = owner;
                db.AddSubCategory(category);
                db.Save();
                return RedirectToAction("Index");
            }
            return View(category);
        }

    

        //
        // GET: /ManageCategories/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /ManageCategories/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                int userId = (int)Membership.GetUser().ProviderUserKey;
                User owner = db.FindUser(userId);
                category.Owner = owner;
                db.AddCategory(category);
                db.Save();
                return RedirectToAction("Index");
            }
            return View(category);
        }
        
        //
        // GET: /ManageCategories/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Category category = db.FindCategory(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // POST: /ManageCategories/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                db.EditCategory(category);
                db.Save();
                return RedirectToAction("Index");
            }
            return View(category);
        }
        
        //
        // GET: /ManageCategories/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Category category = db.FindCategory(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // POST: /ManageCategories/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.RemoveCategoryAndSubWithNotes(id);
            db.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcNotes/Controllers/MyNotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MvcNotes.Models;
using MvcNotes.Repository;

namespace MvcNotes.Controllers
{

    [Authorize]
    public class MyNotesController : Controller
    {
        private NotesRepository db = new NotesRepository();
        //
        // GET: /MyNotes/

        public ActionResult Index()
        {
            int userId = (int)Membership.GetUser().ProviderUserKey;
            List<Category> lstCats = db.GelAllCategories(userId);
            return View(lstCats);
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcNotes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Заметки", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                            <li>@Html.ActionLink("Мои заметки", "Index", "MyNotes")</li>
                            <li>@Html.ActionLink("Мои категории", "Index", "ManageCategories")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Сервис управления заметками</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>